### ISSUE TITLE
AnnDataReadError with run_OnClass_example.py 

### ISSUE THREAD

**Issue by lgeistlinger** [wangshenguiuc/OnClass#12]
Hi after running `run_OnClass_example.py` I am trying to read in the h5ad file that is written out [in the last line of the script](https://github.com/wangshenguiuc/OnClass/blob/07b2917dbdf01a1de54771de3383bbaa4bb2f283/run_OnClass_example.py#L57). I am using the `read_h5ad` function from the `anndata` package.

I obtain the following error:

```
AnnDataReadError: Above error raised while reading key '/layers' of type <class 'h5py._hl.group.Group'> from /.
```

implicating that the layers got somehow miswritten.

**Comment by canergen** [comment]
This is an error with different versions of AnnData. Most likely not a problem with OnClass.
