### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by cartographerJ** [wangshenguiuc/OnClass#3]
Hi just wanted to note some issues I have run into trying run this.  

1) seems to be a combination of tensorflow 1 and 2 - I was able to move fully to tensorflow2.

2) function dont have same parameters as onclass documentation eg. read_data() doesnt have the suggest param for training data return_AnnData = True - can obviously just read this in with anndata

3) the header on some of the files makes using the suggested imports in the onclass documentation not work

4) there is no actually code (that I can find in this repo) for the function  write_anndata_data()

**Comment by cartographerJ** [comment]
bump

**Comment by wangshenguiuc** [comment]
Sorry for a very late reply! I has recently left Stanford and my Stanford email is also not active anymore. I will work on this and give you an update within a week. Apologize again!

**Comment by redst4r** [comment]
in the meantime, reverting back to 1c4c3f332ae3effceae46c1bb82a6104e92901cd is an option. seems like the example code at least runs through

**Comment by wangshenguiuc** [comment]
We have updated the doc and software. Please check the new doc here https://onclass.readthedocs.io/en/latest/installation.html

We also have a notebook here https://github.com/wangshenguiuc/OnClass/blob/master/run_OnClass_example.ipynb
