### ISSUE TITLE
Trouble finding `utils` and `config`

### ISSUE THREAD

**Issue by bschilder** [wangshenguiuc/OnClass#5]
Hello, 

Thanks for a great tool! I'm having some issues finding the `utils` and `config` modules referenced in the examples. 

I'm running OnClass via the pip installation within a conda env. Btw, feel free to reshare this conda env if you think users will find it helpful:
https://github.com/bschilder/scKirby/blob/main/inst/conda/onclass.yml 

I also came across this usage in a [search through the repo](https://github.com/wangshenguiuc/OnClass/search?q=utils), but it didn't seem to work in my case: 

```python
from OnClass.utils import *
```

Thanks in advance, 
Brian

**Comment by bschilder** [comment]
Ah i see, these seem to be additional files outside of the package:
https://github.com/wangshenguiuc/OnClass/blob/master/utils.py
https://github.com/wangshenguiuc/OnClass/blob/master/config.py

Will these be integrated into the pip distribution of OnClass at some point?

**Comment by wangshenguiuc** [comment]
Thank you, Brain. We will integrate them into the pip distribution soon. Thank you for sharing your conda env. I will also integrate that into our repo. This is very helpful!

**Comment by bschilder** [comment]
Many thanks, and no problem!
