### ISSUE TITLE
Char-level LSTM 

### ISSUE THREAD

**Issue by bschilder** [wangshenguiuc/OnClass#7]
Hello, 

I'm keen to use the Char-level LSTM for uncontrolled to controlled celltype annotation mapping, [referenced in the documentation](https://onclass.readthedocs.io/en/latest/howtouse.html).

However, I can't seem to find the section related to this. Apologies if I'm missing it somehow, or it's been called something else.

Best, 
Brian

**Comment by wangshenguiuc** [comment]
Hi Brian,

I have updated the documentation.
You can set nlp_mapping = True in the read_data function. This will use char-level LSTM to do the mapping

Let us know if there is anything we can help!
Sheng

**Comment by bschilder** [comment]
Excellent, thank you!
