### ISSUE TITLE
Error installation: package dependency conflicts

### ISSUE THREAD

**Issue by hurleyLi** [wangshenguiuc/OnClass#8]
Hi,
I tried to install OnClass, but has the dependency conflicts error for `intervaltree`.  
When I have `intervaltree==2.1.0`, I got this error:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 4.2.1 requires intervaltree>=3.0.2, but you have intervaltree 2.1.0 which is incompatible.
```

But when I have `intervaltree==3.1.0`, I got this error:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scanorama 1.7.1 requires intervaltree==2.1.0, but you have intervaltree 3.1.0 which is incompatible.
```

It seems `scanorama 1.7.1` and `spyder 4.2.1` requires different version of `intervaltree`.
Could you please let me know how to fix this issue?
Thanks!
Hurley

**Comment by wangshenguiuc** [comment]
My intervaltree is 2.1.0. I don't seem to have spyder package.

Here is a conda yml file built by bschilder you can use to install OnClass https://github.com/bschilder/scKirby/blob/main/inst/conda/onclass.yml 

Another solution is to just clone the github repo and run it without doing the pip install. You don't need to install scanorama if you only want to train on a single dataset.


I will look more into this intervaltree issue soon.
